### ISSUE TITLE
Applicative-like operators for Allocators

### ISSUE THREAD

**Issue by jwaldmann** [apunktbau/co4#112]
This would be nice: for `data T = Foo T1 | Bar T2 T3`, write in Control.Applicative style
```
( Foo <$> someT1allocator ) <|> (Bar <$> someT2alloc <*> someT3alloc)
```
we would need something like
```
instance Applicative TAllocator where pure = fromKnown
```
but this will not work since the `FromKnown a =>` precondition is needed.

(It's the same problem with `instance Monad Set`: you cannot write `Ord a =>`)

OK, so we cannot have the Applicative operator names, but we can have the operators.
I think `CO4.Allocator.Typed.union` is `<|>` - do we have `<$>`? 

Could CO4 generate automatically these functions:
```
aFoo :: TAllocator T1 -> TAllocator T
aBar :: TAllocator T2 -> TAllocator T3 -> TAllocator T
```
for user-defined types, and also for predefined (`aCons`, `aJust`, `aTuple2`, ..)

**Comment by apunktbau** [comment]
> Could CO4 generate automatically these functions for user-defined types

CO4 already generates these:

    knownFoo :: TAllocator T1 -> TAllocator T
    knownBar :: TAllocator T2 -> TAllocator T3 -> TAllocator T
    knownTuple2 :: TAllocator a -> TAllocator b -> TAllocator ((,) a b)
    ...

**Comment by jwaldmann** [comment]
Ah, good, I forgot about `knownFoo`. Then it's fine.
