### ISSUE TITLE
deriving Eq

### ISSUE THREAD

**Issue by jwaldmann** [apunktbau/co4#4]
for all user-defined algebraic data types, equalitiy would be nice:

* deriving Eq for the "original" program (so it can be used when testing the answer)
* the standard implementation of '==' for the transformed program (so it can be used in constraints)

(Note: We don't want the full type class machinery, just '=='.)

A design question is whether 
* the compiler adds 'deriving (Show, Eq)' silently
* the user has to write 'deriving (Show, Eq)' explicitly

Writing might be better: then the constraint program *is* a correctly typed Haskell program

**Comment by jwaldmann** [comment]
(bump this issue) please clarify the status of `==` for user-defined data types.

When I naively use `==` I get 

      Algorithms.HindleyMilner.W: Can not deduce type for '=='

**Comment by apunktbau** [comment]
> please clarify the status of == for user-defined data types

There used to be a hack that provided `==` for user-defined types, but it was unstable and did not work for polymorphic functions. So I dropped it, i.e., one must manually write comparison functions for user-defined types.

In my opinion, the best solution would be implementing type inference for type classes and then do some kind of type-class-instantiation. But this seems to be alot of work.

**Comment by jwaldmann** [comment]
OK. Leave type classes for future work.
